export const ADD_TO_FUNC_HISTORY = 'ADD_TO_FUNC_HISTORY';
export const CLEAR_HISTORY = 'CLEAR_HISTORY';
export const ADD_TO_CLASS_HISTORY = 'ADD_TO_CLASS_HISTORY';
export const CHANGE_THEME = 'CHANGE_THEME';
